const DATA_URL = 'data/products.json';
const state = { products: [], filter: 'Alle', query: '', purchased: JSON.parse(localStorage.getItem('baitermin-purchased') || '{}') };
const fmt = new Intl.NumberFormat('da-DK', { style: 'currency', currency: 'DKK', minimumFractionDigits: 2 });
const labels = { buy:'Køb nu', conditional:'Afhænger af valg', later:'Senere', hold:'Afvent' };
function lowest(p){ return p.offers?.length ? [...p.offers].sort((a,b)=>a.priceDkk-b.priceDkk)[0] : null; }
function eligible(p){ return p.status !== 'hold' && p.offers?.length; }
function save(){ localStorage.setItem('baitermin-purchased', JSON.stringify(state.purchased)); }
function renderStats(){const tracked=state.products.filter(eligible);const all=tracked.reduce((s,p)=>s+lowest(p).priceDkk,0);const bought=tracked.filter(p=>state.purchased[p.id]).reduce((s,p)=>s+lowest(p).priceDkk,0);const remaining=tracked.filter(p=>!state.purchased[p.id]).reduce((s,p)=>s+lowest(p).priceDkk,0);const count=tracked.filter(p=>state.purchased[p.id]).length;document.querySelector('#totalAll').textContent=fmt.format(all);document.querySelector('#totalBought').textContent=fmt.format(bought);document.querySelector('#totalRemaining').textContent=fmt.format(remaining);document.querySelector('#progress').textContent=`${Math.round((count/Math.max(1,tracked.length))*100)}%`;document.querySelector('#progressDetail').textContent=`${count} af ${tracked.length} dele købt`;}
function renderFilters(){const cats=['Alle',...new Set(state.products.map(p=>p.category))];const el=document.querySelector('#filters');el.innerHTML=cats.map(c=>`<button data-cat="${c}" class="${state.filter===c?'active':''}">${c}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.filter=b.dataset.cat;renderFilters();renderProducts();});}
function renderProducts(){const q=state.query.trim().toLowerCase();const list=state.products.filter(p=>state.filter==='Alle'||p.category===state.filter).filter(p=>!q||`${p.name} ${p.category} ${p.note} ${(p.offers||[]).map(o=>o.seller).join(' ')}`.toLowerCase().includes(q)).sort((a,b)=>a.order-b.order);const root=document.querySelector('#products');root.innerHTML=list.map(p=>{const offers=[...(p.offers||[])].sort((a,b)=>a.priceDkk-b.priceDkk).slice(0,3);const checked=!!state.purchased[p.id];return `<article class="product ${checked?'purchased':''}" data-id="${p.id}"><div class="product-head"><div class="order">${String(p.order).padStart(2,'0')}</div><div><p class="category">${p.category}</p><div class="title-row"><h2>${p.name}</h2><span class="badge ${p.status}">${labels[p.status]}</span></div><p class="note">${p.note}</p></div><label class="buycheck"><input type="checkbox" ${checked?'checked':''} ${p.status==='hold'?'disabled':''}><span>${checked?'Købt':'Markér købt'}</span></label></div>${offers.length?`<div class="offers">${offers.map((o,i)=>`<div class="offer ${i===0?'best':''}"><div class="seller">${o.seller}</div><div class="price">${fmt.format(o.priceDkk)}</div><div class="native">${o.priceNative}</div><div class="tag">${o.tag||''}</div><a href="${o.url}" target="_blank" rel="noopener">Åbn tilbud ↗</a></div>`).join('')}</div>`:`<div class="empty">Ingen tilbud endnu — denne del står med vilje på pause.</div>`}</article>`}).join('');root.querySelectorAll('.product').forEach(card=>{const input=card.querySelector('input[type=checkbox]');if(!input||input.disabled)return;input.onchange=()=>{state.purchased[card.dataset.id]=input.checked;save();renderProducts();renderStats();};});}
async function init(){try{const res=await fetch(DATA_URL,{cache:'no-store'});if(!res.ok)throw new Error('Kunne ikke hente produktdata');const data=await res.json();state.products=data.products;document.querySelector('#updated').textContent=`Opdateret ${new Date(data.updatedAt).toLocaleString('da-DK')}`;renderFilters();renderProducts();renderStats();}catch(err){document.querySelector('#products').innerHTML=`<div class="empty">${err.message}</div>`;}}
document.querySelector('#search').addEventListener('input',e=>{state.query=e.target.value;renderProducts();});
document.querySelector('#reset').onclick=()=>{if(confirm('Nulstil alle markeringer som købt?')){state.purchased={};save();renderProducts();renderStats();}};
init();